### ISSUE TITLE
GitHub stars/forks are not refreshed on Porcupine page

### ISSUE THREAD

**Issue by AnnaVantVeer** [TimVanMourik/GiraffeTools#125]
**Describe the bug**
The stars/forks on the Porcupine page do not display correct number that belongs with the project that you are looking at. 

**To Reproduce**
1. Go to an example project
2. Go to a new project
3. see the stars/forks numbers of the example project

**Expected behavior**
refreshed stars/forks

**Screenshots**
<img width="2215" alt="screen shot 2019-01-22 at 14 30 35" src="https://user-images.githubusercontent.com/18264896/51540513-e9338800-1e56-11e9-93b4-8f0d7d2666c9.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser : chrome
 - Version  71.0.3578.98 (Official Build) (64-bit)

**Additional context**
Spoke to Tim about this via email as well.

**Comment by TimVanMourik** [comment]
Thanks @AnnaVantVeer! I realised this a while ago but forgot about it as it wasn't urgent enough to look into before launching at Coastal Coding and OpenMR Benelux. So it's really good that you brought to my attention again. I think it's fixed now (in commit d0172a972ae2ccbb779c26db85b34ca67c5ce1fc)

The nerd reason for the problem: the previous buttons were embedded buttons that tried to minimise the number of GitHub API calls by remembering the responses. Because the structure of the embedding did not conform to the GiraffeTools implementation, the buttons weren't updated. 

Solution: the GitHub buttons have been implemented from scratch in the current framework. 

I'll close this issue on confirmation of the functionality working.
