### ISSUE TITLE
Add a search bar on the left and right side?

### ISSUE THREAD

**Issue by Losses** [TimVanMourik/GiraffeTools#98]
**Describe the solution you'd like**
Adding a search bar on the left and right sidebar, users can get tools and options easily. :D

**Comment by TimVanMourik** [comment]
In order to implement this, we first need to have searchable terms. In other words, the nodes need to be annotated with what they represent. So the roadmap for this issue is roughly:

* Adapt application to include perhaps a 'keywords' field
* Annotate nodes with keywords
* Include search functionality in application

**Comment by TimVanMourik** [comment]
Search bar added, so closing this issue. Thanks for the feature request @Losses.

I'm aware that the current search behaviour is rather limited. I only search in the titles of nodes. I'd be happy to expand it if Nipype ever gets keyword annotation.
